### ISSUE TITLE
TFT_eSPI_Button error in IDE

### ISSUE THREAD

**Issue by itsdannyit** [justcallmekoko/ESP32Marauder#610]
after i do the exact same in these issues and i got this plz help me fix this 
Log IDE:

c:/users/gigabyte/appdata/local/arduino15/packages/esp32/tools/xtensa-esp32-elf-gcc/esp-2021r2-patch5-8.4.0/bin/../lib/gcc/xtensa-esp32-elf/8.4.0/../../../../xtensa-esp32-elf/bin/ld.exe: C:\Users\Gigabyte\AppData\Local\Temp\arduino\sketches\8184CDF450CA63F19E693235AE4B784E\sketch\objs.a(WiFiScan.cpp.o):(.literal._ZN8WiFiScan16eapolMonitorMainEj+0x20): undefined reference to `TFT_eSPI_Button::press(bool)'
c:/users/gigabyte/appdata/local/arduino15/packages/esp32/tools/xtensa-esp32-elf-gcc/esp-2021r2-patch5-8.4.0/bin/../lib/gcc/xtensa-esp32-elf/8.4.0/../../../../xtensa-esp32-elf/bin/ld.exe: C:\Users\Gigabyte\AppData\Local\Temp\arduino\sketches\8184CDF450CA63F19E693235AE4B784E\sketch\objs.a(WiFiScan.cpp.o):(.literal._ZN8WiFiScan16eapolMonitorMainEj+0x24): undefined reference to `TFT_eSPI_Button::justPressed()'
c:/users/gigabyte/appdata/local/arduino15/packages/esp32/tools/xtensa-esp32-elf-gcc/esp-2021r2-patch5-8.4.0/bin/../lib/gcc/xtensa-esp32-elf/8.4.0/../../../../xtensa-esp32-elf/bin/ld.exe: C:\Users\Gigabyte\AppData\Local\Temp\arduino\sketches\8184CDF450CA63F19E693235AE4B784E\sketch\objs.a(WiFiScan.cpp.o):(.literal._ZN8WiFiScan16eapolMonitorMainEj+0x28): undefined reference to `TFT_eSPI_Button::justReleased()'
c:/users/gigabyte/appdata/local/arduino15/packages/esp32/tools/xtensa-esp32-elf-gcc/esp-2021r2-patch5-8.4.0/bin/../lib/gcc/xtensa-esp32-elf/8.4.0/../../../../xtensa-esp32-elf/bin/ld.exe: C:\Users\Gigabyte\AppData\Local\Temp\arduino\sketches\8184CDF450CA63F19E693235AE4B784E\sketch\objs.a(WiFiScan.cpp.o): in function `WiFiScan::eapolMonitorMain(unsigned int)':
C:\Users\Gigabyte\Downloads\Compressed\marauder\workingman\esp32_marauder/WiFiScan.cpp:4499: undefined reference to `TFT_eSPI_Button::press(bool)'
c:/users/gigabyte/appdata/local/arduino15/packages/esp32/tools/xtensa-esp32-elf-gcc/esp-2021r2-patch5-8.4.0/bin/../lib/gcc/xtensa-esp32-elf/8.4.0/../../../../xtensa-esp32-elf/bin/ld.exe: C:\Users\Gigabyte\Downloads\Compressed\marauder\workingman\esp32_marauder/WiFiScan.cpp:4506: undefined reference to `TFT_eSPI_Button::justPressed()'
c:/users/gigabyte/appdata/local/arduino15/packages/esp32/tools/xtensa-esp32-elf-gcc/esp-2021r2-patch5-8.4.0/bin/../lib/gcc/xtensa-esp32-elf/8.4.0/../../../../xtensa-esp32-elf/bin/ld.exe: C:\Users\Gigabyte\Downloads\Compressed\marauder\workingman\esp32_marauder/WiFiScan.cpp:4512: undefined reference to `TFT_eSPI_Button::justReleased()'
c:/users/gigabyte/appdata/local/arduino15/packages/esp32/tools/xtensa-esp32-elf-gcc/esp-2021r2-patch5-8.4.0/bin/../lib/gcc/xtensa-esp32-elf/8.4.0/../../../../xtensa-esp32-elf/bin/ld.exe: C:\Users\Gigabyte\AppData\Local\Temp\arduino\sketches\8184CDF450CA63F19E693235AE4B784E\sketch\objs.a(Display.cpp.o):(.literal._ZN7Display26tftDrawChannelScaleButtonsEi+0xc): undefined reference to `TFT_eSPI_Button::initButton(TFT_eSPI*, short, short, unsigned short, unsigned short, unsigned short, unsigned short, unsigned short, char*, unsigned char)'
c:/users/gigabyte/appdata/local/arduino15/packages/esp32/tools/xtensa-esp32-elf-gcc/esp-2021r2-patch5-8.4.0/bin/../lib/gcc/xtensa-esp32-elf/8.4.0/../../../../xtensa-esp32-elf/bin/ld.exe: C:\Users\Gigabyte\AppData\Local\Temp\arduino\sketches\8184CDF450CA63F19E693235AE4B784E\sketch\objs.a(Display.cpp.o):(.literal._ZN7Display26tftDrawChannelScaleButtonsEi+0x10): undefined reference to `TFT_eSPI_Button::setLabelDatum(short, short, unsigned char)'
c:/users/gigabyte/appdata/local/arduino15/packages/esp32/tools/xtensa-esp32-elf-gcc/esp-2021r2-patch5-8.4.0/bin/../lib/gcc/xtensa-esp32-elf/8.4.0/../../../../xtensa-esp32-elf/bin/ld.exe: C:\Users\Gigabyte\AppData\Local\Temp\arduino\sketches\8184CDF450CA63F19E693235AE4B784E\sketch\objs.a(Display.cpp.o):(.literal._ZN7Display26tftDrawChannelScaleButtonsEi+0x14): undefined reference to `TFT_eSPI_Button::drawButton(bool, String)'
c:/users/gigabyte/appdata/local/arduino15/packages/esp32/tools/xtensa-esp32-elf-gcc/esp-2021r2-patch5-8.4.0/bin/../lib/gcc/xtensa-esp32-elf/8.4.0/../../../../xtensa-esp32-elf/bin/ld.exe: C:\Users\Gigabyte\AppData\Local\Temp\arduino\sketches\8184CDF450CA63F19E693235AE4B784E\sketch\objs.a(Display.cpp.o):(.literal._ZN7DisplayC2Ev+0x10): undefined reference to `TFT_eSPI_Button::TFT_eSPI_Button()'
c:/users/gigabyte/appdata/local/arduino15/packages/esp32/tools/xtensa-esp32-elf-gcc/esp-2021r2-patch5-8.4.0/bin/../lib/gcc/xtensa-esp32-elf/8.4.0/../../../../xtensa-esp32-elf/bin/ld.exe: C:\Users\Gigabyte\AppData\Local\Temp\arduino\sketches\8184CDF450CA63F19E693235AE4B784E\sketch\objs.a(Display.cpp.o): in function `Display::tftDrawChannelScaleButtons(int)':
C:\Users\Gigabyte\Downloads\Compressed\marauder\workingman\esp32_marauder/Display.cpp:197: undefined reference to `TFT_eSPI_Button::initButton(TFT_eSPI*, short, short, unsigned short, unsigned short, unsigned short, unsigned short, unsigned short, char*, unsigned char)'
c:/users/gigabyte/appdata/local/arduino15/packages/esp32/tools/xtensa-esp32-elf-gcc/esp-2021r2-patch5-8.4.0/bin/../lib/gcc/xtensa-esp32-elf/8.4.0/../../../../xtensa-esp32-elf/bin/ld.exe: C:\Users\Gigabyte\Downloads\Compressed\marauder\workingman\esp32_marauder/Display.cpp:207: undefined reference to `TFT_eSPI_Button::initButton(TFT_eSPI*, short, short, unsigned short, unsigned short, unsigned short, unsigned short, unsigned short, char*, unsigned char)'
c:/users/gigabyte/appdata/local/arduino15/packages/esp32/tools/xtensa-esp32-elf-gcc/esp-2021r2-patch5-8.4.0/bin/../lib/gcc/xtensa-esp32-elf/8.4.0/../../../../xtensa-esp32-elf/bin/ld.exe: C:\Users\Gigabyte\Downloads\Compressed\marauder\workingman\esp32_marauder/Display.cpp:218: undefined reference to `TFT_eSPI_Button::setLabelDatum(short, short, unsigned char)'
c:/users/gigabyte/appdata/local/arduino15/packages/esp32/tools/xtensa-esp32-elf-gcc/esp-2021r2-patch5-8.4.0/bin/../lib/gcc/xtensa-esp32-elf/8.4.0/../../../../xtensa-esp32-elf/bin/ld.exe: C:\Users\Gigabyte\Downloads\Compressed\marauder\workingman\esp32_marauder/Display.cpp:219: undefined reference to `TFT_eSPI_Button::setLabelDatum(short, short, unsigned char)'
c:/users/gigabyte/appdata/local/arduino15/packages/esp32/tools/xtensa-esp32-elf-gcc/esp-2021r2-patch5-8.4.0/bin/../lib/gcc/xtensa-esp32-elf/8.4.0/../../../../xtensa-esp32-elf/bin/ld.exe: C:\Users\Gigabyte\Downloads\Compressed\marauder\workingman\esp32_marauder/Display.cpp:221: undefined reference to `TFT_eSPI_Button::drawButton(bool, String)'
c:/users/gigabyte/appdata/local/arduino15/packages/esp32/tools/xtensa-esp32-elf-gcc/esp-2021r2-patch5-8.4.0/bin/../lib/gcc/xtensa-esp32-elf/8.4.0/../../../../xtensa-esp32-elf/bin/ld.exe: C:\Users\Gigabyte\Downloads\Compressed\marauder\workingman\esp32_marauder/Display.cpp:222: undefined reference to `TFT_eSPI_Button::drawButton(bool, String)'
c:/users/gigabyte/appdata/local/arduino15/packages/esp32/tools/xtensa-esp32-elf-gcc/esp-2021r2-patch5-8.4.0/bin/../lib/gcc/xtensa-esp32-elf/8.4.0/../../../../xtensa-esp32-elf/bin/ld.exe: C:\Users\Gigabyte\AppData\Local\Temp\arduino\sketches\8184CDF450CA63F19E693235AE4B784E\sketch\objs.a(Display.cpp.o): in function `Display::tftDrawExitScaleButtons()':
C:\Users\Gigabyte\Downloads\Compressed\marauder\workingman\esp32_marauder/Display.cpp:230: undefined reference to `TFT_eSPI_Button::initButton(TFT_eSPI*, short, short, unsigned short, unsigned short, unsigned short, unsigned short, unsigned short, char*, unsigned char)'
c:/users/gigabyte/appdata/local/arduino15/packages/esp32/tools/xtensa-esp32-elf-gcc/esp-2021r2-patch5-8.4.0/bin/../lib/gcc/xtensa-esp32-elf/8.4.0/../../../../xtensa-esp32-elf/bin/ld.exe: C:\Users\Gigabyte\Downloads\Compressed\marauder\workingman\esp32_marauder/Display.cpp:241: undefined reference to `TFT_eSPI_Button::setLabelDatum(short, short, unsigned char)'
c:/users/gigabyte/appdata/local/arduino15/packages/esp32/tools/xtensa-esp32-elf-gcc/esp-2021r2-patch5-8.4.0/bin/../lib/gcc/xtensa-esp32-elf/8.4.0/../../../../xtensa-esp32-elf/bin/ld.exe: C:\Users\Gigabyte\Downloads\Compressed\marauder\workingman\esp32_marauder/Display.cpp:243: undefined reference to `TFT_eSPI_Button::drawButton(bool, String)'
c:/users/gigabyte/appdata/local/arduino15/packages/esp32/tools/xtensa-esp32-elf-gcc/esp-2021r2-patch5-8.4.0/bin/../lib/gcc/xtensa-esp32-elf/8.4.0/../../../../xtensa-esp32-elf/bin/ld.exe: C:\Users\Gigabyte\AppData\Local\Temp\arduino\sketches\8184CDF450CA63F19E693235AE4B784E\sketch\objs.a(Display.cpp.o): in function `Display::Display()':
C:\Users\Gigabyte\Downloads\Compressed\marauder\workingman\esp32_marauder/Display.cpp:6: undefined reference to `TFT_eSPI_Button::TFT_eSPI_Button()'
c:/users/gigabyte/appdata/local/arduino15/packages/esp32/tools/xtensa-esp32-elf-gcc/esp-2021r2-patch5-8.4.0/bin/../lib/gcc/xtensa-esp32-elf/8.4.0/../../../../xtensa-esp32-elf/bin/ld.exe: C:\Users\Gigabyte\AppData\Local\Temp\arduino\sketches\8184CDF450CA63F19E693235AE4B784E\sketch\objs.a(MenuFunctions.cpp.o): in function `MenuFunctions::buttonNotSelected(unsigned char, signed char)':
C:\Users\Gigabyte\Downloads\Compressed\marauder\workingman\esp32_marauder/MenuFunctions.cpp:480: undefined reference to `TFT_eSPI_Button::drawButton(bool, String)'
c:/users/gigabyte/appdata/local/arduino15/packages/esp32/tools/xtensa-esp32-elf-gcc/esp-2021r2-patch5-8.4.0/bin/../lib/gcc/xtensa-esp32-elf/8.4.0/../../../../xtensa-esp32-elf/bin/ld.exe: C:\Users\Gigabyte\AppData\Local\Temp\arduino\sketches\8184CDF450CA63F19E693235AE4B784E\sketch\objs.a(MenuFunctions.cpp.o): in function `MenuFunctions::buttonSelected(unsigned char, signed char)':
C:\Users\Gigabyte\Downloads\Compressed\marauder\workingman\esp32_marauder/MenuFunctions.cpp:487: undefined reference to `TFT_eSPI_Button::drawButton(bool, String)'
c:/users/gigabyte/appdata/local/arduino15/packages/esp32/tools/xtensa-esp32-elf-gcc/esp-2021r2-patch5-8.4.0/bin/../lib/gcc/xtensa-esp32-elf/8.4.0/../../../../xtensa-esp32-elf/bin/ld.exe: C:\Users\Gigabyte\AppData\Local\Temp\arduino\sketches\8184CDF450CA63F19E693235AE4B784E\sketch\objs.a(MenuFunctions.cpp.o): in function `MenuFunctions::buildButtons(Menu*, int, String)':
C:\Users\Gigabyte\Downloads\Compressed\marauder\workingman\esp32_marauder/MenuFunctions.cpp:2355: undefined reference to `TFT_eSPI_Button::TFT_eSPI_Button()'
c:/users/gigabyte/appdata/local/arduino15/packages/esp32/tools/xtensa-esp32-elf-gcc/esp-2021r2-patch5-8.4.0/bin/../lib/gcc/xtensa-esp32-elf/8.4.0/../../../../xtensa-esp32-elf/bin/ld.exe: C:\Users\Gigabyte\Downloads\Compressed\marauder\workingman\esp32_marauder/MenuFunctions.cpp:2361: undefined reference to `TFT_eSPI_Button::initButton(TFT_eSPI*, short, short, unsigned short, unsigned short, unsigned short, unsigned short, unsigned short, char*, unsigned char)'
c:/users/gigabyte/appdata/local/arduino15/packages/esp32/tools/xtensa-esp32-elf-gcc/esp-2021r2-patch5-8.4.0/bin/../lib/gcc/xtensa-esp32-elf/8.4.0/../../../../xtensa-esp32-elf/bin/ld.exe: C:\Users\Gigabyte\Downloads\Compressed\marauder\workingman\esp32_marauder/MenuFunctions.cpp:2372: undefined reference to `TFT_eSPI_Button::setLabelDatum(short, short, unsigned char)'
c:/users/gigabyte/appdata/local/arduino15/packages/esp32/tools/xtensa-esp32-elf-gcc/esp-2021r2-patch5-8.4.0/bin/../lib/gcc/xtensa-esp32-elf/8.4.0/../../../../xtensa-esp32-elf/bin/ld.exe: C:\Users\Gigabyte\AppData\Local\Temp\arduino\sketches\8184CDF450CA63F19E693235AE4B784E\sketch\objs.a(MenuFunctions.cpp.o): in function `MenuFunctions::addNodes(Menu*, String, unsigned short, Menu*, int, std::function<void ()>, bool, String)':
C:\Users\Gigabyte\Downloads\Compressed\marauder\workingman\esp32_marauder/MenuFunctions.cpp:2343: undefined reference to `TFT_eSPI_Button::TFT_eSPI_Button()'
c:/users/gigabyte/appdata/local/arduino15/packages/esp32/tools/xtensa-esp32-elf-gcc/esp-2021r2-patch5-8.4.0/bin/../lib/gcc/xtensa-esp32-elf/8.4.0/../../../../xtensa-esp32-elf/bin/ld.exe: C:\Users\Gigabyte\AppData\Local\Temp\arduino\sketches\8184CDF450CA63F19E693235AE4B784E\sketch\objs.a(MenuFunctions.cpp.o): in function `MenuFunctions::displayCurrentMenu(unsigned char)':
C:\Users\Gigabyte\Downloads\Compressed\marauder\workingman\esp32_marauder/MenuFunctions.cpp:2416: undefined reference to `TFT_eSPI_Button::drawButton(bool, String)'
c:/users/gigabyte/appdata/local/arduino15/packages/esp32/tools/xtensa-esp32-elf-gcc/esp-2021r2-patch5-8.4.0/bin/../lib/gcc/xtensa-esp32-elf/8.4.0/../../../../xtensa-esp32-elf/bin/ld.exe: C:\Users\Gigabyte\Downloads\Compressed\marauder\workingman\esp32_marauder/MenuFunctions.cpp:2418: undefined reference to `TFT_eSPI_Button::drawButton(bool, String)'
collect2.exe: error: ld returned 1 exit status
Multiple libraries were found for "SD.h"
  Used: C:\Users\Gigabyte\AppData\Local\Arduino15\packages\esp32\hardware\esp32\2.0.14\libraries\SD
  Not used: C:\Users\Gigabyte\AppData\Local\Arduino15\libraries\SD
exit status 1

Compilation error: exit status 1

**Comment by itsdannyit** [comment]
ok i fix it when upgrade the "TFT_eSPI" by Bodmer to 2.4.79 and it does compile, now it giving me a white and it rebooting

**Comment by itsdannyit** [comment]
fix the boot loop by using the User_setup.h by koko fork and boot loop fix, still white screen

**Comment by itsdannyit** [comment]
Tuoch still work as i randomly click and it open setting cause it print in the serial port
