### ISSUE TITLE
compiling error 'esp_event_send_internal'

### ISSUE THREAD

**Issue by boris20571** [justcallmekoko/ESP32Marauder#1025]
hi there,

still got the issue with compiling the bin. file in ARDUINO 2.3.7. as in issue reporrt #712 

exit status 1
'esp_event_send_internal' was not declared in this scope

<img width="574" height="196" alt="Image" src="https://github.com/user-attachments/assets/b0d5ab61-74be-479d-881d-f10476cbc0ba" />

Firmware: ESP32Marauder-1.9.0
Device: cyd_2432S028_2usb
OS: IOS MAC Ventura 13.7.8 (22H730)

I want to change is the GPS Tx & Rx values in the file "configs.h".
from to
Tx:21 Tx:1
Rx:22 Rx:3

<img width="431" height="219" alt="Image" src="https://github.com/user-attachments/assets/14949916-8164-4075-ad67-326e3f9be432" />

Because the GPS is not working with Firmware v1.9.0, but it is still working fine with Firmware v1.8.9.

Any ideas?

BR
Boris

**Comment by justcallmekoko** [comment]
This is because for non-dual band hardware, we still compile on arduino-core 2.0.11
